os: Visual Studio 2015

platform:
  - x86

environment:
  matrix:
    - ARCH: x86
      PYTHON: "C:\\Python35"
    - ARCH: x64
      PYTHON: "C:\\Python35-x64"

skip_branch_with_pr: true

install:
  - git submodule update --init --recursive

  - set PATH=%cd%;%PYTHON%;%PYTHON%\Scripts;%PATH%
  - pip install meson ninja

  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%

build_script:
  - ps: $env:OTS_VERSION = C:\cygwin\bin\grep -m1 version meson.build | C:\cygwin\bin\cut --% -d"'" -f2
  - set ARCHIVE=ots-%OTS_VERSION%-windows

  - meson --buildtype=release --backend=ninja --prefix=%cd% --bindir=%ARCHIVE% build
  - where link
  - ninja -C build

test_script:
  - ninja -C build test

after_build:
  - ninja -C build install
  - 7z a %ARCHIVE%.zip %ARCHIVE%

artifacts:
  - path: /ots-*-windows.zip/

deploy:
  provider: GitHub
  auth_token:
    secure: "Mcg1hVyyuN6rVAvSj55POVX4C14JhWwL9UrP2tQAFTqk3Muke0ttyfYKZfeU4zAi"
  draft: true
  on:
    appveyor_repo_tag: true
    ARCH: x64
