language: cpp

dist: trusty
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      # Need to use gold linker due to bug in Ubuntu gcc-5 package.
      env: MATRIX_EVAL="CC='gcc-5 -fuse-ld=gold' && CXX='g++-5 -fuse-ld=gold'"
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang

env:
  global:
    - secure: "KXfgO6PGxlEcNJHLxMPxZvUtxkCX8V/ZD5plXYxCPaKamTWJknuAvFJAPukhIDTX+1AcUxEBvG/QLszEIiPemPRbDmj4knG5y5GINLx/Jjl3ePKXzYdfc6G/G/QnH3YEQ/GBp6Gvf6w2d+IB3dgEyn9td8VaOt0XmNvW4l76nm4="

git:
  submodules: false

sudo: false

addons:
  apt:
    packages:
      - fonts-inconsolata
      - fonts-takao-gothic
      - fonts-takao-mincho
      - fonts-takao-pgothic
  coverity_scan:
    project:
      name: "khaledhosny/ots"
      description: "Build submitted via Travis CI"
    notification_email: khaledhosny@eglug.org
    build_command_prepend: "./configure; make clean"
    build_command: "make -j 4"
    branch_pattern: coverity

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./autogen.sh

script:
  - ./configure --enable-debug
  - make
  - make -j check || (cat test-suite.log && false)
